apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-prod
  namespace: argocd
  labels:
    env: prod
spec:
  project: default
  source:
    repoURL: https://github.com/tiqsclass6/kubernetes-projects-2026.git
    targetRevision: project-3
    path: manifests/splunk/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
