apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-prod-cheat
  namespace: argocd
  labels:
    env: prod
spec:
  project: splunk-prod-cheat
  source:
    repoURL: https://github.com/tiqsclass6/kubernetes-projects-2026.git
    targetRevision: project-3
    path: splunk/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: splunk-dev
