apiVersion: v1
kind: Secret
metadata:
  name: key-auth-super-secret
  namespace: kong
  labels:
    konghq.com/credential: key-auth
  annotations:
    kubernetes.io/ingress.class: kong
type: Opaque
stringData:
  key: super-secret-key