apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: lizzo-devote
  namespace: kong
  annotations:
    kubernetes.io/ingress.class: kong
username: lizzo-devote
credentials:
  - key-auth-super-secret