apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: my-rate-limiting-plugin
  namespace: chewbacca
  annotations:
    kubernetes.io/ingress.class: kong
plugin: rate-limiting
config:
  minute: 5
  policy: local