apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: splunk-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/<ORG>/<REPO>.git
    targetRevision: main
    path: splunk/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: splunk-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


#kubectl apply -f splunk-dev-app.yaml