apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-example
spec:
  replicas: 3                        # only override replicas
  template:
    spec:
      containers:
      - name: nginx                    # must match base container name
        image: splunk/splunk:latest    # override image
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"