apiVersion: apps/v1
kind: Deployment
metadata:
  name: splunk-example
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx                  # Must match base
        image: nginx:1.14.2         # Use this for testing
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"