apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: "2026-04-07T06:35:39Z"
    generation: 1
    labels:
      kustomize.toolkit.fluxcd.io/name: splunk-dev
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: splunk-web-tls
    namespace: splunk-dev
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: splunk
      uid: 63ef3f7d-c3d9-4865-ab53-989fc614bdc4
    resourceVersion: "1775543740149775011"
    uid: 77bc9853-b531-4241-960e-8f9a798b88eb
  spec:
    dnsNames:
    - splunk-dev.example.com
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: selfsigned
    secretName: splunk-web-tls
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2026-04-07T06:35:40Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-06T06:35:39Z"
    notBefore: "2026-04-07T06:35:39Z"
    renewalTime: "2026-06-06T06:35:39Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""