apiVersion: v1
items:
- apiVersion: cert-manager.io/v1
  kind: Certificate
  metadata:
    creationTimestamp: "2026-04-11T15:18:14Z"
    generation: 1
    labels:
      kustomize.toolkit.fluxcd.io/name: splunk-dev
      kustomize.toolkit.fluxcd.io/namespace: flux-system
    name: splunk-web-tls
    namespace: splunk-dev
    ownerReferences:
    - apiVersion: networking.k8s.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Ingress
      name: splunk
      uid: f61a4340-9d30-4587-b8d5-87a58aa6ac31
    resourceVersion: "1775920695851999011"
    uid: 4bef2f4c-40e6-4427-82c7-7c46391dba18
  spec:
    dnsNames:
    - splunk-dev.example.com
    issuerRef:
      group: cert-manager.io
      kind: ClusterIssuer
      name: selfsigned
    secretName: splunk-web-tls
    usages:
    - digital signature
    - key encipherment
  status:
    conditions:
    - lastTransitionTime: "2026-04-11T15:18:15Z"
      message: Certificate is up to date and has not expired
      observedGeneration: 1
      reason: Ready
      status: "True"
      type: Ready
    notAfter: "2026-07-10T15:18:15Z"
    notBefore: "2026-04-11T15:18:15Z"
    renewalTime: "2026-06-10T15:18:15Z"
    revision: 1
kind: List
metadata:
  resourceVersion: ""