apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"source.toolkit.fluxcd.io/v1","kind":"GitRepository","metadata":{"annotations":{},"name":"github-platform","namespace":"flux-system"},"spec":{"interval":"1m","ref":{"branch":"project-4"},"url":"https://github.com/tiqsclass6/kubernetes-projects-2026.git"}}
    reconcile.fluxcd.io/requestedAt: "2026-04-11T11:22:26.6928564-04:00"
  creationTimestamp: "2026-04-11T15:18:09Z"
  finalizers:
  - finalizers.fluxcd.io
  generation: 1
  name: github-platform
  namespace: flux-system
  resourceVersion: "1775920946958127019"
  uid: 503e56c0-d585-41ef-a421-ee4b776cb10e
spec:
  interval: 1m
  ref:
    branch: project-4
  timeout: 60s
  url: https://github.com/tiqsclass6/kubernetes-projects-2026.git
status:
  artifact:
    digest: sha256:90491dc40488c43557d2e10c6013f847cdbcff03222c2ee40fbdc8ec7798834c
    lastUpdateTime: "2026-04-11T15:18:13Z"
    path: gitrepository/flux-system/github-platform/ca8d237f54db4cf21859c2999d2115962c599f47.tar.gz
    revision: project-4@sha1:ca8d237f54db4cf21859c2999d2115962c599f47
    size: 71242
    url: http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/github-platform/ca8d237f54db4cf21859c2999d2115962c599f47.tar.gz
  conditions:
  - lastTransitionTime: "2026-04-11T15:18:13Z"
    message: stored artifact for revision 'project-4@sha1:ca8d237f54db4cf21859c2999d2115962c599f47'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: Ready
  - lastTransitionTime: "2026-04-11T15:18:13Z"
    message: stored artifact for revision 'project-4@sha1:ca8d237f54db4cf21859c2999d2115962c599f47'
    observedGeneration: 1
    reason: Succeeded
    status: "True"
    type: ArtifactInStorage
  lastHandledReconcileAt: "2026-04-11T11:22:26.6928564-04:00"
  observedGeneration: 1